sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    # before_install:

    #   - openssl aes-256-cbc -K $encrypted_0a87eabj907c_key -iv $encrypted_0c35eebf403c_iv -in srv-account.json.enc -out srv-account.json -d
    #   - curl https://sdk.cloud.google.com | bash > /dev/null;
    #   - source $HOME/google-cloud-sdk/path.bash.inc
    #   - gcloud components update kubectl
    #   - gcloud auth activate-service-account --key-file srv-account.json
    #   - gcloud config set project sahafrica
    #   - gcloud config set compute/zone us-central1-a
    #   - gcloud container clusters get-credentials sahafrica
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker build -t abdelmounaimazz/auth-test -f ./auth/Dockerfile.dev ./auth
#   - docker build -t abdelmounaimazz/orders-test -f ./orders/Dockerfile.dev ./orders
#   - docker build -t abdelmounaimazz/products-test -f ./products/Dockerfile.dev ./products

script:
  - docker build -t abdelmounaimazz/auth:latest -t abdelmounaimazz/auth:$SHA -f ./auth/Dockerfile ./auth
  - docker build -t abdelmounaimazz/client:latest -t abdelmounaimazz/client:$SHA -f ./client/Dockerfile ./client
  - docker build -t abdelmounaimazz/expiration:latest -t abdelmounaimazz/expiration:$SHA -f ./expiration/Dockerfile ./expiration
  - docker build -t abdelmounaimazz/orders:latest -t abdelmounaimazz/orders:$SHA -f ./orders/Dockerfile ./orders
  - docker build -t abdelmounaimazz/payments:latest -t abdelmounaimazz/payments:$SHA -f ./payments/Dockerfile ./payments
  - docker build -t abdelmounaimazz/products:latest -t abdelmounaimazz/products:$SHA -f ./products/Dockerfile ./products

  - docker push abdelmounaimazz/auth:latest
  - docker push abdelmounaimazz/client:latest
  - docker push abdelmounaimazz/orders:latest
  - docker push abdelmounaimazz/products:latest
  - docker push abdelmounaimazz/expiration:latest
  - docker push abdelmounaimazz/payments:latest

  - docker push abdelmounaimazz/auth:$SHA
  - docker push abdelmounaimazz/client:$SHA
  - docker push abdelmounaimazz/orders:$SHA
  - docker push abdelmounaimazz/peoducts:$SHA
  - docker push abdelmounaimazz/payments:$SHA
  - docker push abdelmounaimazz/expiration:$SHA
  # - docker run -e CI=true abdelmounaimazz/auth-test
  # - docker run -e CI=true abdelmounaimazz/auth-test
  # - docker run -e CI=true abdelmounaimazz/orders-test
  # - docker run -e CI=true abdelmounaimazz/products-test
# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   on:
#     branch: master
